# export LANG=ja_JP.utf-8
# export LC_ALL=ja_JP.utf-8
export LANG=en_US.utf-8
export LC_ALL=en_US.utf-8
export TERM=xterm-256color
export EDITOR=vim
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
export XDG_CACHE_HOME=~/.cache
export DOTPATH=~/.dotfiles
export GOPATH=~/.go
export PIPENV_VENV_IN_PROJECT=true
