export LANG=ja_JP.utf-8
export LC_ALL=ja_JP.utf-8
export TERM=xterm-256color
export DOTPATH=$HOME/dotfiles
export EDITOR=vim
export XDG_CONFIG_HOME=$HOME/.config
export GOPATH=$HOME/go
export FZF_ALT_C_OPTS="--select-1 --exit-0"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
