cask_args appdir: '/Applications'

tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/cask-versions'
tap 'homebrew/cask'

brew 'coreutils'
brew 'zsh'
brew 'neovim'
brew 'tmux'
brew 'zplug'
brew 'git'
brew 'reattach-to-user-namespace'
brew 'zsh-completions'
brew 'hub'
brew 'ghq'
brew 'fzf'
brew 'emojify'
brew 'jq'
brew 'fpp'

cask 'alacritty'
cask 'dash'
cask 'alfred'
cask 'visual-studio-code'
cask 'docker'
cask 'docker-toolbox'
