[[plugins]]
repo = 'Shougo/dein.vim'


#----------------------------------------------
# Git
#----------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'let g:airline#extensions#branch#enabled=1'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#----------------------------------------------
# Tmux
#----------------------------------------------
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
  let g:tmux_navigator_no_mappings = 1
  let g:tmux_navigator_save_on_switch = 2

  nnoremap <silent> <C-h> :TmuxNavigateLeft<cr>
  nnoremap <silent> <C-j> :TmuxNavigateDown<cr>
  nnoremap <silent> <C-k> :TmuxNavigateUp<cr>
  nnoremap <silent> <C-l> :TmuxNavigateRight<cr>
  nnoremap <silent> <C-/> :TmuxNavigatePrevious<cr>
'''

[[plugins]]
repo = 'tpope/vim-obsession'


#----------------------------------------------
# Tags
#----------------------------------------------
[[plugins]]
repo = 'szw/vim-tags'
hook_add = '''
  let g:vim_tags_project_tags_command = "/usr/local/bin/ctags -R {OPTIONS} {DIRECTORY} 2>/dev/null"
  let g:vim_tags_gems_tags_command = "/usr/local/bin/ctags -R {OPTIONS} `bundle show --paths` 2>/dev/null"

  nnoremap <Leader>h :split<CR> :exe("tjump ".expand('<cword>'))<CR>
  nnoremap <Leader>v :vsplit<CR> :exe("tjump ".expand('<cword>'))<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  let g:tagbar_width = 30
  set statusline=%F%m%r%h%w\%=%{tagbar#currenttag('[%s]','')}\[Pos=%v,%l]\[Len=%L]
'''


#----------------------------------------------
# Unite.vim
#----------------------------------------------
[[plugins]]
repo = 'Shougo/unite.vim'


#----------------------------------------------
# NERDTree.vim
#----------------------------------------------
# ファイルのツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " ファイル指定なしのとき自動起動
  let g:NERDTreeShowHidden=1
  " ブックマーク
  let g:NERDTreeShowBookmarks=1

  nmap <Leader>n :NERDTreeToggle<CR>
'''

# NERDTree のタブ間共有
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
	if argc() == 0
		let g:nerdtree_tabs_open_on_console_startup=1
	endif
'''


#----------------------------------------------
# Others
#----------------------------------------------
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  set splitbelow
  set splitright
'''
hook_post_source = 'nmap <Leader>r :Quickrun'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  nmap <Leader>b <Plug>(openbrowser-smart-search)
  vmap <Leader>b <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
  nmap j <Plug>(accelerated_jk_gj)
  nmap k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
    if !exists('g:context_filetype#filetypes')
        let g:context_filetype#filetypes = {}
    endif
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['Shougo/context_filetype.vim']

[[plugins]]
repo = 'AndrewRadev/switch.vim'
hook_add = 'let g:switch_mapping = "S"'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

# repo = 'vim-scripts/AnsiEsc.vim'
# repo = 'tyru/caw.vim'


#----------------------------------------------
# Colorschemes
#----------------------------------------------
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_source = 'let g:one_dark_termcolors=16'
