[[plugins]]
repo = 'Shougo/dein.vim'

#----------------------------------------------
# Completion & Snippets
#----------------------------------------------
[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  let g:acp_enableAtStartup = 0
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#sources#syntax#min_keyword_length = 3

  " Plugin key-mappings.
  inoremap <expr><C-g> neocomplete#undo_completion()
  inoremap <expr><C-l> neocomplete#complete_common_string()
  inoremap <expr><tab>  pumvisible() ? "\<C-n>" : "\<TAB>"
'''

# repo = 'Shougo/neosnippet.vim'
# repo = 'Shougo/neosnippet-snippets'


#----------------------------------------------
# Tab & Status Line
#----------------------------------------------
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline#extensions#tabline#enabled=1
  let g:airline#extensions#tabline#left_sep=' '
  let g:airline#extensions#tabline#left_alt_sep=' '
  " タブバーの右領域を非表示
  "let g:airline#extensions#tabline#show_splits = 0
  "let g:airline#extensions#tabline#show_tab_type = 0
  "let g:airline#extensions#tabline#show_close_button = 0
'''


#----------------------------------------------
# Git
#----------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'let g:airline#extensions#branch#enabled=1'


#----------------------------------------------
# Markdown
#----------------------------------------------
[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'let g:vim_markdown_folding_disabled=1'

[[plugins]]
repo = 'kannokanno/previm'


#----------------------------------------------
# Unite.vim
#----------------------------------------------
# [[plugins]]
# repo = 'kannokanno/previm'
# hook_add = '''
#     let g:unite_enable_start_insert = 1
#     let g:unite_enable_split_vertically = 0
#     let g:unite_winwidth = 40
#
#     nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file file/new<CR>
#     nnoremap <silent> ,um :<C-u>Unite  file_mru <CR>
#     nnoremap <silent> ,urc :<C-u>Unite file_rec/async:app/controllers/ <CR>
#     nnoremap <silent> ,urfc :<C-u>Unite file file/new -input=app/controllers/ <CR>
#     nnoremap <silent> ,urm :<C-u>Unite file_rec/async:app/models/ <CR>
#     nnoremap <silent> ,urfm :<C-u>Unite file file/new -input=app/models/ <CR>
#     nnoremap <silent> ,urv :<C-u>Unite file_rec/async:app/views/ <CR>
#     nnoremap <silent> ,urfv :<C-u>Unite file file/new -input=app/views/ <CR>
#     nnoremap <silent> ,urs :<C-u>Unite file_rec/async:app/assets/stylesheets/ <CR>
#     nnoremap <silent> ,urfs :<C-u>Unite file file/new -input=app/assets/stylesheets/ <CR>
#     nnoremap <silent> ,urj :<C-u>Unite file_rec/async:app/assets/javascripts/ <CR>
#     nnoremap <silent> ,urfj :<C-u>Unite file file/new -input=app/assets/javascripts/ <CR>
#     nnoremap <silent> ,uro :<C-u>Unite file_rec/async:config/ <CR>
#     nnoremap <silent> ,urfo :<C-u>Unite file file/new -input=config/ <CR>
#     nnoremap <silent> ,url :<C-u>Unite file_rec/async:lib/ <CR>
#     nnoremap <silent> ,urfl :<C-u>Unite file file/new -input=lib/ <CR>
#     nnoremap <silent> ,urr :<C-u>Unite file_rec/async:spec/ <CR>
#     nnoremap <silent> ,urfr :<C-u>Unite file file/new -input=spec/ <CR
# '''


#----------------------------------------------
# NERDTree.vim
#----------------------------------------------
# ファイルのツリー表示
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " ファイル指定なしのとき自動起動
  let g:NERDTreeShowHidden=1
  " ブックマーク
  let g:NERDTreeShowBookmarks=1

  nmap <Leader>n :NERDTreeToggle<CR>
'''

# NERDTree のタブ間共有
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
	if argc() == 0
		let g:nerdtree_tabs_open_on_console_startup=1
	endif
'''


#----------------------------------------------
# Others
#----------------------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  set splitbelow
  set splitright
'''
hook_post_source = 'nmap <Leader>r :Quickrun'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  nmap <Leader>b <Plug>(openbrowser-smart-search)
  vmap <Leader>b <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
  nmap j <Plug>(accelerated_jk_gj)
  "xmap j <Plug>(accelerated_jk_gj)
  nmap k <Plug>(accelerated_jk_gk)
  "xmap k <Plug>(accelerated_jk_gk)
'''

# [[plugins]]
# repo = 'Shougo/context_filetype.vim'
# hook_add = '''
#     if !exists('g:context_filetype#filetypes')
#         let g:context_filetype#filetypes = {}
#     endif
# '''

# [[plugins]]
# repo = 'osyo-manga/vim-precious'
# depends = ['Shougo/context_filetype.vim']


# repo = 'vim-scripts/AnsiEsc.vim'
# repo = 'tyru/caw.vim'


#----------------------------------------------
# Colorschemes
#----------------------------------------------
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_source = 'let g:one_dark_termcolors=16'
