#----------------------------------------------
# Completion & Snippets
#----------------------------------------------
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
hook_add = '''
  let g:acp_enableAtStartup = 0
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#sources#syntax#min_keyword_length = 3

  " For Ruby
  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'
  let g:rsenseUseomniFunc = 1

  " Plugin key-mappings.
  inoremap <expr><C-g> neocomplete#undo_completion()
  inoremap <expr><C-l> neocomplete#complete_common_string()
  inoremap <expr><tab>  pumvisible() ? "\<C-n>" : "\<TAB>"
'''
on_i = 1

# repo = 'Shougo/neosnippet.vim'
# repo = 'Shougo/neosnippet-snippets'


#----------------------------------------------
# Rails
#----------------------------------------------
repo = 'tpope/vim-rails'
# repo = 'todesking/ruby_hl_lvar.vim'


#----------------------------------------------
# HTML
#----------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html']

[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['html']


#----------------------------------------------
# Markdown
#----------------------------------------------
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']


#----------------------------------------------
# TeX
#----------------------------------------------
[[plugins]]
repo = 'lervag/vimtex'
hook_source = '''
  let g:vimtex_compiler_latexmk = {
        \ 'background': 1,
        \ 'build_dir': '',
        \ 'continuous': 1,
        \ 'options': [
        \    '-pdfdvi',
        \    '-verbose',
        \    '-file-line-error',
        \    '-synctex=1',
        \    '-interaction=nonstopmode',
        \],
        \}
  let g:vimtex_compiler_latexmk = {'callback': 0}
  let g:vimtex_latexmk_continuous = 1
  let g:vimtex_latexmk_options = '-pdfdvi'
  let g:tex_conceal = ''
  let g:vimtex_fold_envs = 0
  let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  " let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
'''
on_ft = ['tex']


#----------------------------------------------
# Syntax
#----------------------------------------------
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'let g:vim_markdown_folding_disabled=1'
on_ft = ['markdown']
