#----------------------------------------------
# Snippets
#----------------------------------------------
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_source = '''
  let g:neosnippet#snippets_directory = '$DOTPATH/vim/snippets/, $XDG_CACHE_HOME/dein/repos/github.com/Shougo/neosnippet-snippets/neosnippets/'
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif

  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''
on_i = 1
depends = 'neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#----------------------------------------------
# Unite & Denite
#----------------------------------------------
[[plugins]]
repo = 'Shougo/unite.vim'
if = "!has('nvim')"

[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"

#----------------------------------------------
# Python
#----------------------------------------------
[[plugins]]
repo  = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

#----------------------------------------------
# Rails
#----------------------------------------------
[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo  = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

#----------------------------------------------
# TeX
#----------------------------------------------
[[plugins]]
repo = 'lervag/vimtex'
hook_source = '''
  let g:vimtex_compiler_latexmk = {
        \ 'background': 1,
        \ 'build_dir': '',
        \ 'continuous': 1,
        \ 'options': [
        \    '-pdfdvi',
        \    '-verbose',
        \    '-file-line-error',
        \    '-synctex=1',
        \    '-interaction=nonstopmode',
        \],
        \}
  let g:vimtex_compiler_latexmk = {'callback': 0}
  let g:vimtex_latexmk_continuous = 1
  let g:vimtex_latexmk_options = '-pdfdvi'
  let g:tex_conceal = ''
  let g:vimtex_fold_envs = 0
  let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  " let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
'''
on_ft = 'tex'

#----------------------------------------------
# Others
#----------------------------------------------
[[plugins]]
repo = 'cohama/lexima.vim'
hook_source = '''
  " LaTeX settings
  call lexima#add_rule({'char': '$', 'input_after': '$', 'filetype': 'tex'})
  call lexima#add_rule({'char': '$', 'at': '\%#\$', 'leave': 1, 'filetype': 'tex'})
  call lexima#add_rule({'char': '<BS>', 'at': '\$\%#\$', 'delete': 1, 'filetype': 'tex'})
'''
on_i = 1
