if has('nvim')
  let g:python_host_prog  = expand('/usr/local/bin/python')
  let g:python3_host_prog = expand('/usr/local/bin/python3')
endif

if !exists('g:vscode')
  source $DOTPATH/vim/plug.vim
  source $DOTPATH/vim/appearance.vim
  source $DOTPATH/vim/edit.vim
  source $DOTPATH/vim/keymaps.vim
  source $DOTPATH/vim/others.vim
endif
