#!/bin/bash

set -eu

error() {
  echo $1 1>&2
  echo 'Installation failed.' 1>&2
  exit 1
}

has() {
  return $(type "$1" > /dev/null 2>&1)
}


dir=~/.dotfiles
[ -d $dir ] && error "**warning** $dir will be deleted!!"

if has 'brew'; then
  brew update && brew upgrade
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
has 'brew' || error "Can't install Homebrew."

if has 'git'; then
  git clone --recursive https://github.com/shikibu9419/.dotfiles $dir
elif has 'curl'; then
  tarball=https://github.com/shikibu9419/.dotfiles/tarball/master

  curl -fsSL $tarball -o $dir.tar.gz
  tar -zxvf $dir.tar.gz --strip-components=1 -C $dir
  rm -f $dir.tar.gz
else
  error "Neither 'git' nor 'curl' were found.\nPlease install one of them to install dotfiles."
fi

echo "Dotfiles were installed on $dir!"
echo
