add_newline = true
scan_timeout = 10

[directory]
truncation_length = 8

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
untracked = ""
modified = ""

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[azure]
disabled = true
