add_newline = true
scan_timeout = 10

[directory]
truncation_length = 8

[git_status]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[azure]
disabled = true
