#!/bin/zsh

if status=$(cd $1 && git status 2> /dev/null); then
  branch=$(echo $status | awk 'NR==1 {print $3}')
  case $status in
    *Changes\ not\ staged*) state="#[bg=yellow, fg=black] ✗ "
      ;;
    *Changes\ to\ be\ committed*) state="#[bg=cyan, fg=black] + "
      ;;
    *) state="#[bg=green, fg=black] ✔ "
      ;;
  esac
  echo "#[bg=default, fg=cyan] ${branch}#[default] ${state}"
fi
